// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"
class Vtop_core;


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:
    // CELLS
    Vtop_core* __PVT__gpu__DOT__cores__BRA__0__KET____DOT__core_instance;
    Vtop_core* __PVT__gpu__DOT__cores__BRA__1__KET____DOT__core_instance;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(start,0,0);
        VL_OUT8(done,0,0);
        VL_IN8(device_control_write_enable,0,0);
        VL_IN8(device_control_data,7,0);
        VL_OUT8(program_mem_read_valid,0,0);
        VL_OUT8(program_mem_read_address,7,0);
        VL_IN8(program_mem_read_ready,0,0);
        VL_OUT8(data_mem_read_valid,3,0);
        VL_IN8(data_mem_read_ready,3,0);
        VL_OUT8(data_mem_write_valid,3,0);
        VL_IN8(data_mem_write_ready,3,0);
        CData/*0:0*/ gpu__DOT__clk;
        CData/*0:0*/ gpu__DOT__reset;
        CData/*0:0*/ gpu__DOT__start;
        CData/*0:0*/ gpu__DOT__done;
        CData/*0:0*/ gpu__DOT__device_control_write_enable;
        CData/*7:0*/ gpu__DOT__device_control_data;
        CData/*0:0*/ gpu__DOT__program_mem_read_valid;
        CData/*7:0*/ gpu__DOT__program_mem_read_address;
        CData/*0:0*/ gpu__DOT__program_mem_read_ready;
        CData/*3:0*/ gpu__DOT__data_mem_read_valid;
        CData/*3:0*/ gpu__DOT__data_mem_read_ready;
        CData/*3:0*/ gpu__DOT__data_mem_write_valid;
        CData/*3:0*/ gpu__DOT__data_mem_write_ready;
        CData/*7:0*/ gpu__DOT__thread_count;
        CData/*1:0*/ gpu__DOT__core_start;
        CData/*1:0*/ gpu__DOT__core_reset;
        CData/*1:0*/ gpu__DOT__core_done;
        CData/*5:0*/ gpu__DOT__core_thread_count;
        CData/*1:0*/ gpu__DOT__sv2v_tmp_dispatch_instance_core_start;
        CData/*1:0*/ gpu__DOT__sv2v_tmp_dispatch_instance_core_reset;
        CData/*5:0*/ gpu__DOT__sv2v_tmp_dispatch_instance_core_thread_count;
        CData/*7:0*/ gpu__DOT__lsu_read_valid;
        CData/*7:0*/ gpu__DOT__lsu_read_ready;
        CData/*7:0*/ gpu__DOT__lsu_write_valid;
        CData/*7:0*/ gpu__DOT__lsu_write_ready;
        CData/*1:0*/ gpu__DOT__fetcher_read_valid;
        CData/*1:0*/ gpu__DOT__fetcher_read_ready;
        CData/*7:0*/ gpu__DOT__sv2v_tmp_data_memory_controller_consumer_write_ready;
        CData/*7:0*/ gpu__DOT__sv2v_tmp_data_memory_controller_consumer_read_ready;
        CData/*1:0*/ gpu__DOT__sv2v_tmp_program_memory_controller_consumer_read_ready;
        CData/*3:0*/ gpu__DOT__cores__BRA__0__KET____DOT__core_lsu_read_valid;
        CData/*3:0*/ gpu__DOT__cores__BRA__0__KET____DOT__core_lsu_read_ready;
        CData/*3:0*/ gpu__DOT__cores__BRA__0__KET____DOT__core_lsu_write_valid;
        CData/*3:0*/ gpu__DOT__cores__BRA__0__KET____DOT__core_lsu_write_ready;
        CData/*0:0*/ gpu__DOT__cores__BRA__0__KET____DOT__sv2v_tmp_core_instance_done;
        CData/*0:0*/ gpu__DOT__cores__BRA__0__KET____DOT__sv2v_tmp_core_instance_program_mem_read_valid;
        CData/*7:0*/ gpu__DOT__cores__BRA__0__KET____DOT__sv2v_tmp_core_instance_program_mem_read_address;
        CData/*3:0*/ gpu__DOT__cores__BRA__0__KET____DOT__sv2v_tmp_core_instance_data_mem_read_valid;
        CData/*3:0*/ gpu__DOT__cores__BRA__0__KET____DOT__sv2v_tmp_core_instance_data_mem_write_valid;
        CData/*3:0*/ gpu__DOT__cores__BRA__1__KET____DOT__core_lsu_read_valid;
        CData/*3:0*/ gpu__DOT__cores__BRA__1__KET____DOT__core_lsu_read_ready;
        CData/*3:0*/ gpu__DOT__cores__BRA__1__KET____DOT__core_lsu_write_valid;
        CData/*3:0*/ gpu__DOT__cores__BRA__1__KET____DOT__core_lsu_write_ready;
        CData/*0:0*/ gpu__DOT__cores__BRA__1__KET____DOT__sv2v_tmp_core_instance_done;
        CData/*0:0*/ gpu__DOT__cores__BRA__1__KET____DOT__sv2v_tmp_core_instance_program_mem_read_valid;
        CData/*7:0*/ gpu__DOT__cores__BRA__1__KET____DOT__sv2v_tmp_core_instance_program_mem_read_address;
        CData/*3:0*/ gpu__DOT__cores__BRA__1__KET____DOT__sv2v_tmp_core_instance_data_mem_read_valid;
        CData/*3:0*/ gpu__DOT__cores__BRA__1__KET____DOT__sv2v_tmp_core_instance_data_mem_write_valid;
        CData/*0:0*/ gpu__DOT__dcr_instance__DOT__clk;
        CData/*0:0*/ gpu__DOT__dcr_instance__DOT__reset;
        CData/*0:0*/ gpu__DOT__dcr_instance__DOT__device_control_write_enable;
    };
    struct {
        CData/*7:0*/ gpu__DOT__dcr_instance__DOT__device_control_data;
        CData/*7:0*/ gpu__DOT__dcr_instance__DOT__thread_count;
        CData/*7:0*/ gpu__DOT__dcr_instance__DOT__device_conrol_register;
        CData/*0:0*/ gpu__DOT__dispatch_instance__DOT__clk;
        CData/*0:0*/ gpu__DOT__dispatch_instance__DOT__reset;
        CData/*0:0*/ gpu__DOT__dispatch_instance__DOT__start;
        CData/*7:0*/ gpu__DOT__dispatch_instance__DOT__thread_count;
        CData/*1:0*/ gpu__DOT__dispatch_instance__DOT__core_done;
        CData/*1:0*/ gpu__DOT__dispatch_instance__DOT__core_start;
        CData/*1:0*/ gpu__DOT__dispatch_instance__DOT__core_reset;
        CData/*5:0*/ gpu__DOT__dispatch_instance__DOT__core_thread_count;
        CData/*0:0*/ gpu__DOT__dispatch_instance__DOT__done;
        CData/*7:0*/ gpu__DOT__dispatch_instance__DOT__total_blocks;
        CData/*7:0*/ gpu__DOT__dispatch_instance__DOT__blocks_dispatched;
        CData/*7:0*/ gpu__DOT__dispatch_instance__DOT__blocks_done;
        CData/*0:0*/ gpu__DOT__dispatch_instance__DOT__start_execution;
        CData/*2:0*/ gpu__DOT__dispatch_instance__DOT____Vlvbound_h4c6e9b06__0;
        CData/*0:0*/ gpu__DOT__data_memory_controller__DOT__clk;
        CData/*0:0*/ gpu__DOT__data_memory_controller__DOT__reset;
        CData/*7:0*/ gpu__DOT__data_memory_controller__DOT__consumer_read_valid;
        CData/*7:0*/ gpu__DOT__data_memory_controller__DOT__consumer_read_ready;
        CData/*7:0*/ gpu__DOT__data_memory_controller__DOT__consumer_write_valid;
        CData/*7:0*/ gpu__DOT__data_memory_controller__DOT__consumer_write_ready;
        CData/*3:0*/ gpu__DOT__data_memory_controller__DOT__mem_read_valid;
        CData/*3:0*/ gpu__DOT__data_memory_controller__DOT__mem_read_ready;
        CData/*3:0*/ gpu__DOT__data_memory_controller__DOT__mem_write_valid;
        CData/*3:0*/ gpu__DOT__data_memory_controller__DOT__mem_write_ready;
        CData/*7:0*/ gpu__DOT__data_memory_controller__DOT__consumer_mutex;
        CData/*7:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__0__KET____DOT__consumer_req_offset;
        CData/*1:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__0__KET____DOT__sv2v_autoblock_5__DOT___sv2v_jump;
        CData/*0:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__0__KET____DOT__sv2v_autoblock_5__DOT__sv2v_autoblock_6__DOT__sv2v_autoblock_7__DOT__sv2v_autoblock_8__DOT__tag_valid;
        CData/*0:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__0__KET____DOT__sv2v_autoblock_5__DOT__sv2v_autoblock_6__DOT__sv2v_autoblock_7__DOT__sv2v_autoblock_8__DOT__sv2v_autoblock_9__DOT__req_line_valid;
        CData/*7:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__1__KET____DOT__consumer_req_offset;
        CData/*1:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__1__KET____DOT__sv2v_autoblock_5__DOT___sv2v_jump;
        CData/*0:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__1__KET____DOT__sv2v_autoblock_5__DOT__sv2v_autoblock_6__DOT__sv2v_autoblock_7__DOT__sv2v_autoblock_8__DOT__tag_valid;
        CData/*0:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__1__KET____DOT__sv2v_autoblock_5__DOT__sv2v_autoblock_6__DOT__sv2v_autoblock_7__DOT__sv2v_autoblock_8__DOT__sv2v_autoblock_9__DOT__req_line_valid;
        CData/*7:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__2__KET____DOT__consumer_req_offset;
        CData/*1:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__2__KET____DOT__sv2v_autoblock_5__DOT___sv2v_jump;
        CData/*0:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__2__KET____DOT__sv2v_autoblock_5__DOT__sv2v_autoblock_6__DOT__sv2v_autoblock_7__DOT__sv2v_autoblock_8__DOT__tag_valid;
        CData/*0:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__2__KET____DOT__sv2v_autoblock_5__DOT__sv2v_autoblock_6__DOT__sv2v_autoblock_7__DOT__sv2v_autoblock_8__DOT__sv2v_autoblock_9__DOT__req_line_valid;
        CData/*7:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__3__KET____DOT__consumer_req_offset;
        CData/*1:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__3__KET____DOT__sv2v_autoblock_5__DOT___sv2v_jump;
        CData/*0:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__3__KET____DOT__sv2v_autoblock_5__DOT__sv2v_autoblock_6__DOT__sv2v_autoblock_7__DOT__sv2v_autoblock_8__DOT__tag_valid;
        CData/*0:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__3__KET____DOT__sv2v_autoblock_5__DOT__sv2v_autoblock_6__DOT__sv2v_autoblock_7__DOT__sv2v_autoblock_8__DOT__sv2v_autoblock_9__DOT__req_line_valid;
        CData/*7:0*/ gpu__DOT__data_memory_controller__DOT____Vlvbound_h14c04415__0;
        CData/*7:0*/ gpu__DOT__data_memory_controller__DOT____Vlvbound_h98b46d85__0;
        CData/*7:0*/ gpu__DOT__data_memory_controller__DOT____Vlvbound_h0c71622f__0;
        CData/*7:0*/ gpu__DOT__data_memory_controller__DOT____Vlvbound_h05961d59__0;
        CData/*0:0*/ gpu__DOT__program_memory_controller__DOT__clk;
        CData/*0:0*/ gpu__DOT__program_memory_controller__DOT__reset;
        CData/*1:0*/ gpu__DOT__program_memory_controller__DOT__consumer_read_valid;
        CData/*1:0*/ gpu__DOT__program_memory_controller__DOT__consumer_read_ready;
        CData/*1:0*/ gpu__DOT__program_memory_controller__DOT__consumer_write_valid;
        CData/*1:0*/ gpu__DOT__program_memory_controller__DOT__consumer_write_ready;
        CData/*0:0*/ gpu__DOT__program_memory_controller__DOT__mem_read_valid;
        CData/*7:0*/ gpu__DOT__program_memory_controller__DOT__mem_read_address;
        CData/*0:0*/ gpu__DOT__program_memory_controller__DOT__mem_read_ready;
        CData/*0:0*/ gpu__DOT__program_memory_controller__DOT__mem_write_valid;
        CData/*7:0*/ gpu__DOT__program_memory_controller__DOT__mem_write_address;
        CData/*0:0*/ gpu__DOT__program_memory_controller__DOT__mem_write_ready;
        CData/*1:0*/ gpu__DOT__program_memory_controller__DOT__consumer_mutex;
        CData/*7:0*/ gpu__DOT__program_memory_controller__DOT__genblk1__BRA__0__KET____DOT__consumer_req_offset;
        CData/*1:0*/ gpu__DOT__program_memory_controller__DOT__genblk1__BRA__0__KET____DOT__sv2v_autoblock_5__DOT___sv2v_jump;
        CData/*0:0*/ gpu__DOT__program_memory_controller__DOT__genblk1__BRA__0__KET____DOT__sv2v_autoblock_5__DOT__sv2v_autoblock_6__DOT__sv2v_autoblock_7__DOT__sv2v_autoblock_8__DOT__tag_valid;
    };
    struct {
        CData/*0:0*/ gpu__DOT__program_memory_controller__DOT__genblk1__BRA__0__KET____DOT__sv2v_autoblock_5__DOT__sv2v_autoblock_6__DOT__sv2v_autoblock_7__DOT__sv2v_autoblock_8__DOT__sv2v_autoblock_9__DOT__req_line_valid;
        CData/*0:0*/ __Vdly__gpu__DOT__dispatch_instance__DOT__start_execution;
        CData/*1:0*/ __Vdly__gpu__DOT__dispatch_instance__DOT__core_start;
        CData/*1:0*/ __Vdly__gpu__DOT__dispatch_instance__DOT__core_reset;
        CData/*7:0*/ __Vdly__gpu__DOT__data_memory_controller__DOT__genblk1__BRA__0__KET____DOT__consumer_req_offset;
        CData/*7:0*/ __Vdly__gpu__DOT__data_memory_controller__DOT__genblk1__BRA__1__KET____DOT__consumer_req_offset;
        CData/*7:0*/ __Vdly__gpu__DOT__data_memory_controller__DOT__genblk1__BRA__2__KET____DOT__consumer_req_offset;
        CData/*7:0*/ __Vdly__gpu__DOT__data_memory_controller__DOT__genblk1__BRA__3__KET____DOT__consumer_req_offset;
        CData/*7:0*/ __Vdly__gpu__DOT__program_memory_controller__DOT__mem_read_address;
        CData/*7:0*/ __Vdly__gpu__DOT__program_memory_controller__DOT__genblk1__BRA__0__KET____DOT__consumer_req_offset;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v0;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v0;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v1;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v2;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v0;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v0;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v1;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v1;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v2;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v1;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v3;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v4;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v5;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v3;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v3;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v4;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v4;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v5;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v2;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v6;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v7;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v8;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v6;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v6;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v7;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v7;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v8;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v3;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v9;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v10;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v11;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v9;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v9;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v10;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v10;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v11;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v4;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v12;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v13;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v14;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v12;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v12;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v13;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v13;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v14;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v5;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v15;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v16;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v17;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v15;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v15;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v16;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v16;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v17;
    };
    struct {
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v6;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v18;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v19;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v20;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v18;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v18;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v19;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v19;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v20;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v7;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v21;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v22;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v23;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v21;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v21;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v22;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v22;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v23;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v24;
        CData/*7:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v24;
        CData/*4:0*/ __VdlyLsb__gpu__DOT__data_memory_controller__DOT__cache__v24;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v24;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v24;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v25;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v25;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v25;
        CData/*2:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v26;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v26;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v27;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v27;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v28;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v29;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v30;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v8;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v31;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v32;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v33;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v28;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v28;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v29;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v29;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v30;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v9;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v34;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v35;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v36;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v31;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v31;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v32;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v32;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v33;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v10;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v37;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v38;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v39;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v34;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v34;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v35;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v35;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v36;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v11;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v40;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v41;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v42;
    };
    struct {
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v37;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v37;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v38;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v38;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v39;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v12;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v43;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v44;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v45;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v40;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v40;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v41;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v41;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v42;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v13;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v46;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v47;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v48;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v43;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v43;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v44;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v44;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v45;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v14;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v49;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v50;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v51;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v46;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v46;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v47;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v47;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v48;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v15;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v52;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v53;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v54;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v49;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v49;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v50;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v50;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v51;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v55;
        CData/*7:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v52;
        CData/*4:0*/ __VdlyLsb__gpu__DOT__data_memory_controller__DOT__cache__v52;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v52;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v52;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v56;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v53;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v53;
        CData/*2:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v54;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v54;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v55;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v58;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v59;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v60;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v61;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v16;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v62;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v63;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v64;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v56;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v56;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v57;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v57;
    };
    struct {
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v58;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v17;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v65;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v66;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v67;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v59;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v59;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v60;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v60;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v61;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v18;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v68;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v69;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v70;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v62;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v62;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v63;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v63;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v64;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v19;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v71;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v72;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v73;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v65;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v65;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v66;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v66;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v67;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v20;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v74;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v75;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v76;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v68;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v68;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v69;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v69;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v70;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v21;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v77;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v78;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v79;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v71;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v71;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v72;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v72;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v73;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v22;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v80;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v81;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v82;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v74;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v74;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v75;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v75;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v76;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v23;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v83;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v84;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v85;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v77;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v77;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v78;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v78;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v79;
    };
    struct {
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v86;
        CData/*7:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v80;
        CData/*4:0*/ __VdlyLsb__gpu__DOT__data_memory_controller__DOT__cache__v80;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v80;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v80;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v87;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v81;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v81;
        CData/*2:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v82;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v82;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v83;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v89;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v90;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v91;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v92;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v24;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v93;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v94;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v95;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v84;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v84;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v85;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v85;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v86;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v25;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v96;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v97;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v98;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v87;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v87;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v88;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v88;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v89;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v26;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v99;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v100;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v101;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v90;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v90;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v91;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v91;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v92;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v27;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v102;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v103;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v104;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v93;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v93;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v94;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v94;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v95;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v28;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v105;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v106;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v107;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v96;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v96;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v97;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v97;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v98;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v29;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v108;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v109;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v110;
    };
    struct {
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v99;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v99;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v100;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v100;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v101;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v30;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v111;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v112;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v113;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v102;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v102;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v103;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v103;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v104;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__current_consumer__v31;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v114;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v115;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v116;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v105;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v105;
        CData/*1:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v106;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v106;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v107;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v117;
        CData/*7:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v108;
        CData/*4:0*/ __VdlyLsb__gpu__DOT__data_memory_controller__DOT__cache__v108;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v108;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v108;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v118;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v109;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__cache__v109;
        CData/*2:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v110;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v110;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__data_memory_controller__DOT__cache__v111;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v120;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v121;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v122;
        CData/*0:0*/ __VdlySet__gpu__DOT__data_memory_controller__DOT__controller_state__v123;
        CData/*0:0*/ __VdlySet__gpu__DOT__program_memory_controller__DOT__current_consumer__v0;
        CData/*0:0*/ __VdlySet__gpu__DOT__program_memory_controller__DOT__controller_state__v0;
        CData/*0:0*/ __VdlySet__gpu__DOT__program_memory_controller__DOT__controller_state__v1;
        CData/*0:0*/ __VdlySet__gpu__DOT__program_memory_controller__DOT__controller_state__v2;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__program_memory_controller__DOT__cache__v0;
        CData/*0:0*/ __VdlySet__gpu__DOT__program_memory_controller__DOT__cache__v0;
        CData/*1:0*/ __VdlyVal__gpu__DOT__program_memory_controller__DOT__cache__v1;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__program_memory_controller__DOT__cache__v1;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__program_memory_controller__DOT__cache__v2;
        CData/*0:0*/ __VdlySet__gpu__DOT__program_memory_controller__DOT__current_consumer__v1;
        CData/*0:0*/ __VdlySet__gpu__DOT__program_memory_controller__DOT__controller_state__v3;
        CData/*0:0*/ __VdlySet__gpu__DOT__program_memory_controller__DOT__controller_state__v4;
        CData/*0:0*/ __VdlySet__gpu__DOT__program_memory_controller__DOT__controller_state__v5;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__program_memory_controller__DOT__cache__v3;
        CData/*0:0*/ __VdlySet__gpu__DOT__program_memory_controller__DOT__cache__v3;
        CData/*1:0*/ __VdlyVal__gpu__DOT__program_memory_controller__DOT__cache__v4;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__program_memory_controller__DOT__cache__v4;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__program_memory_controller__DOT__cache__v5;
        CData/*0:0*/ __VdlySet__gpu__DOT__program_memory_controller__DOT__controller_state__v6;
        CData/*5:0*/ __VdlyLsb__gpu__DOT__program_memory_controller__DOT__cache__v6;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__program_memory_controller__DOT__cache__v6;
        CData/*0:0*/ __VdlySet__gpu__DOT__program_memory_controller__DOT__cache__v6;
        CData/*0:0*/ __VdlySet__gpu__DOT__program_memory_controller__DOT__controller_state__v7;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__program_memory_controller__DOT__cache__v7;
        CData/*0:0*/ __VdlySet__gpu__DOT__program_memory_controller__DOT__cache__v7;
        CData/*2:0*/ __VdlyVal__gpu__DOT__program_memory_controller__DOT__cache__v8;
    };
    struct {
        CData/*3:0*/ __VdlyDim0__gpu__DOT__program_memory_controller__DOT__cache__v8;
        CData/*3:0*/ __VdlyDim0__gpu__DOT__program_memory_controller__DOT__cache__v9;
        CData/*0:0*/ __VdlySet__gpu__DOT__program_memory_controller__DOT__controller_state__v9;
        CData/*0:0*/ __VdlySet__gpu__DOT__program_memory_controller__DOT__controller_state__v10;
        CData/*0:0*/ __VdlySet__gpu__DOT__program_memory_controller__DOT__controller_state__v11;
        CData/*0:0*/ __VdlySet__gpu__DOT__program_memory_controller__DOT__controller_state__v12;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu__DOT__cores__BRA__0__KET____DOT__core_instance__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu__DOT__cores__BRA__1__KET____DOT__core_instance__clk__0;
        CData/*0:0*/ __VactContinue;
        VL_IN16(program_mem_read_data,15,0);
        SData/*15:0*/ gpu__DOT__program_mem_read_data;
        SData/*15:0*/ gpu__DOT__core_block_id;
        SData/*15:0*/ gpu__DOT__sv2v_tmp_dispatch_instance_core_block_id;
        SData/*15:0*/ gpu__DOT__fetcher_read_address;
        SData/*15:0*/ gpu__DOT__dispatch_instance__DOT__core_block_id;
        SData/*15:0*/ gpu__DOT__program_memory_controller__DOT__consumer_read_address;
        SData/*15:0*/ gpu__DOT__program_memory_controller__DOT__consumer_write_address;
        SData/*15:0*/ gpu__DOT__program_memory_controller__DOT__mem_read_data;
        SData/*15:0*/ gpu__DOT__program_memory_controller__DOT__mem_write_data;
        SData/*15:0*/ gpu__DOT__program_memory_controller__DOT____Vlvbound_he4e9ff2c__0;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v0;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v3;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v6;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v9;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v12;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v15;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v18;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v21;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v28;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v31;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v34;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v37;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v40;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v43;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v46;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v49;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v56;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v59;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v62;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v65;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v68;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v71;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v74;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v77;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v84;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v87;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v90;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v93;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v96;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v99;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v102;
        SData/*15:0*/ __VdlyVal__gpu__DOT__data_memory_controller__DOT__cache__v105;
        SData/*15:0*/ __VdlyVal__gpu__DOT__program_memory_controller__DOT__cache__v6;
        VL_OUT(data_mem_read_address,31,0);
        VL_IN(data_mem_read_data,31,0);
        VL_OUT(data_mem_write_address,31,0);
        VL_OUT(data_mem_write_data,31,0);
        IData/*31:0*/ gpu__DOT__data_mem_read_address;
        IData/*31:0*/ gpu__DOT__data_mem_read_data;
        IData/*31:0*/ gpu__DOT__data_mem_write_address;
        IData/*31:0*/ gpu__DOT__data_mem_write_data;
    };
    struct {
        IData/*31:0*/ gpu__DOT__fetcher_read_data;
        IData/*31:0*/ gpu__DOT__sv2v_tmp_program_memory_controller_consumer_read_data;
        IData/*31:0*/ gpu__DOT__cores__BRA__0__KET____DOT__core_lsu_read_address;
        IData/*31:0*/ gpu__DOT__cores__BRA__0__KET____DOT__core_lsu_read_data;
        IData/*31:0*/ gpu__DOT__cores__BRA__0__KET____DOT__core_lsu_write_address;
        IData/*31:0*/ gpu__DOT__cores__BRA__0__KET____DOT__core_lsu_write_data;
        IData/*31:0*/ gpu__DOT__cores__BRA__0__KET____DOT__sv2v_tmp_core_instance_data_mem_read_address;
        IData/*31:0*/ gpu__DOT__cores__BRA__0__KET____DOT__sv2v_tmp_core_instance_data_mem_write_address;
        IData/*31:0*/ gpu__DOT__cores__BRA__0__KET____DOT__sv2v_tmp_core_instance_data_mem_write_data;
        IData/*31:0*/ gpu__DOT__cores__BRA__1__KET____DOT__core_lsu_read_address;
        IData/*31:0*/ gpu__DOT__cores__BRA__1__KET____DOT__core_lsu_read_data;
        IData/*31:0*/ gpu__DOT__cores__BRA__1__KET____DOT__core_lsu_write_address;
        IData/*31:0*/ gpu__DOT__cores__BRA__1__KET____DOT__core_lsu_write_data;
        IData/*31:0*/ gpu__DOT__cores__BRA__1__KET____DOT__sv2v_tmp_core_instance_data_mem_read_address;
        IData/*31:0*/ gpu__DOT__cores__BRA__1__KET____DOT__sv2v_tmp_core_instance_data_mem_write_address;
        IData/*31:0*/ gpu__DOT__cores__BRA__1__KET____DOT__sv2v_tmp_core_instance_data_mem_write_data;
        IData/*31:0*/ gpu__DOT__dispatch_instance__DOT__sv2v_autoblock_1__DOT__i;
        IData/*31:0*/ gpu__DOT__dispatch_instance__DOT__sv2v_autoblock_2__DOT__i;
        IData/*31:0*/ gpu__DOT__dispatch_instance__DOT__sv2v_autoblock_3__DOT__i;
        IData/*31:0*/ gpu__DOT__dispatch_instance__DOT__sv2v_autoblock_4__DOT__i;
        IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__mem_read_address;
        IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__mem_read_data;
        IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__mem_write_address;
        IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__mem_write_data;
        IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__sv2v_autoblock_1__DOT__b;
        IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__sv2v_autoblock_2__DOT__b;
        IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__sv2v_autoblock_3__DOT__b;
        IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__sv2v_autoblock_4__DOT__b;
        IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__0__KET____DOT__chunks_read;
        IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__0__KET____DOT__sv2v_autoblock_5__DOT__sv2v_autoblock_6__DOT__j;
        IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__0__KET____DOT__sv2v_autoblock_5__DOT__sv2v_autoblock_6__DOT__sv2v_autoblock_7__DOT___sv2v_value_on_break;
        IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__1__KET____DOT__chunks_read;
        IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__1__KET____DOT__sv2v_autoblock_5__DOT__sv2v_autoblock_6__DOT__j;
        IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__1__KET____DOT__sv2v_autoblock_5__DOT__sv2v_autoblock_6__DOT__sv2v_autoblock_7__DOT___sv2v_value_on_break;
        IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__2__KET____DOT__chunks_read;
        IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__2__KET____DOT__sv2v_autoblock_5__DOT__sv2v_autoblock_6__DOT__j;
        IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__2__KET____DOT__sv2v_autoblock_5__DOT__sv2v_autoblock_6__DOT__sv2v_autoblock_7__DOT___sv2v_value_on_break;
        IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__3__KET____DOT__chunks_read;
        IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__3__KET____DOT__sv2v_autoblock_5__DOT__sv2v_autoblock_6__DOT__j;
        IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__3__KET____DOT__sv2v_autoblock_5__DOT__sv2v_autoblock_6__DOT__sv2v_autoblock_7__DOT___sv2v_value_on_break;
        IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__consumer_read_data;
        IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__consumer_write_data;
        IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__sv2v_autoblock_1__DOT__b;
        IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__sv2v_autoblock_2__DOT__b;
        IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__sv2v_autoblock_3__DOT__b;
        IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__sv2v_autoblock_4__DOT__b;
        IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__genblk1__BRA__0__KET____DOT__chunks_read;
        IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__genblk1__BRA__0__KET____DOT__sv2v_autoblock_5__DOT__sv2v_autoblock_6__DOT__j;
        IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__genblk1__BRA__0__KET____DOT__sv2v_autoblock_5__DOT__sv2v_autoblock_6__DOT__sv2v_autoblock_7__DOT___sv2v_value_on_break;
        IData/*31:0*/ __Vdly__gpu__DOT__data_memory_controller__DOT__mem_read_address;
        IData/*31:0*/ __Vdly__gpu__DOT__data_memory_controller__DOT__genblk1__BRA__0__KET____DOT__chunks_read;
        IData/*31:0*/ __Vdly__gpu__DOT__data_memory_controller__DOT__genblk1__BRA__1__KET____DOT__chunks_read;
        IData/*31:0*/ __Vdly__gpu__DOT__data_memory_controller__DOT__genblk1__BRA__2__KET____DOT__chunks_read;
        IData/*31:0*/ __Vdly__gpu__DOT__data_memory_controller__DOT__genblk1__BRA__3__KET____DOT__chunks_read;
        IData/*31:0*/ __Vdly__gpu__DOT__program_memory_controller__DOT__genblk1__BRA__0__KET____DOT__chunks_read;
        IData/*31:0*/ __VdlyVal__gpu__DOT__program_memory_controller__DOT__cache__v0;
        IData/*31:0*/ __VdlyVal__gpu__DOT__program_memory_controller__DOT__cache__v3;
        IData/*31:0*/ __VactIterCount;
        QData/*63:0*/ gpu__DOT__lsu_read_address;
        QData/*63:0*/ gpu__DOT__lsu_read_data;
        QData/*63:0*/ gpu__DOT__lsu_write_address;
        QData/*63:0*/ gpu__DOT__lsu_write_data;
        QData/*63:0*/ gpu__DOT__sv2v_tmp_data_memory_controller_consumer_read_data;
        QData/*63:0*/ gpu__DOT__data_memory_controller__DOT__consumer_read_address;
    };
    struct {
        QData/*63:0*/ gpu__DOT__data_memory_controller__DOT__consumer_read_data;
        QData/*63:0*/ gpu__DOT__data_memory_controller__DOT__consumer_write_address;
        QData/*63:0*/ gpu__DOT__data_memory_controller__DOT__consumer_write_data;
        VlUnpacked<CData/*7:0*/, 4> gpu__DOT__data_memory_controller__DOT__controller_state;
        VlUnpacked<IData/*21:0*/, 16> gpu__DOT__data_memory_controller__DOT__cache;
        VlUnpacked<CData/*2:0*/, 4> gpu__DOT__data_memory_controller__DOT__current_consumer;
        VlUnpacked<CData/*7:0*/, 1> gpu__DOT__program_memory_controller__DOT__controller_state;
        VlUnpacked<QData/*37:0*/, 16> gpu__DOT__program_memory_controller__DOT__cache;
        VlUnpacked<CData/*0:0*/, 1> gpu__DOT__program_memory_controller__DOT__current_consumer;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<3> __VactTriggered;
    VlTriggerVec<3> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr SData/*15:0*/ gpu__DOT__data_memory_controller__DOT__CACHE_OFFSET_MASK = 0xfffeU;
    static constexpr SData/*15:0*/ gpu__DOT__program_memory_controller__DOT__CACHE_OFFSET_MASK = 0xfffeU;
    static constexpr IData/*31:0*/ gpu__DOT__DATA_MEM_ADDR_BITS = 8U;
    static constexpr IData/*31:0*/ gpu__DOT__DATA_MEM_DATA_BITS = 8U;
    static constexpr IData/*31:0*/ gpu__DOT__DATA_MEM_NUM_CHANNELS = 4U;
    static constexpr IData/*31:0*/ gpu__DOT__PROGRAM_MEM_ADDR_BITS = 8U;
    static constexpr IData/*31:0*/ gpu__DOT__PROGRAM_MEM_DATA_BITS = 0x00000010U;
    static constexpr IData/*31:0*/ gpu__DOT__PROGRAM_MEM_NUM_CHANNELS = 1U;
    static constexpr IData/*31:0*/ gpu__DOT__NUM_CORES = 2U;
    static constexpr IData/*31:0*/ gpu__DOT__THREADS_PER_BLOCK = 4U;
    static constexpr IData/*31:0*/ gpu__DOT__NUM_LSUS = 8U;
    static constexpr IData/*31:0*/ gpu__DOT__NUM_FETCHERS = 2U;
    static constexpr IData/*31:0*/ gpu__DOT__cores__BRA__0__KET____DOT__i = 0U;
    static constexpr IData/*31:0*/ gpu__DOT__cores__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__j = 0U;
    static constexpr IData/*31:0*/ gpu__DOT__cores__BRA__0__KET____DOT__genblk1__BRA__0__KET____DOT__lsu_index = 0U;
    static constexpr IData/*31:0*/ gpu__DOT__cores__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__j = 1U;
    static constexpr IData/*31:0*/ gpu__DOT__cores__BRA__0__KET____DOT__genblk1__BRA__1__KET____DOT__lsu_index = 1U;
    static constexpr IData/*31:0*/ gpu__DOT__cores__BRA__0__KET____DOT__genblk1__BRA__2__KET____DOT__j = 2U;
    static constexpr IData/*31:0*/ gpu__DOT__cores__BRA__0__KET____DOT__genblk1__BRA__2__KET____DOT__lsu_index = 2U;
    static constexpr IData/*31:0*/ gpu__DOT__cores__BRA__0__KET____DOT__genblk1__BRA__3__KET____DOT__j = 3U;
    static constexpr IData/*31:0*/ gpu__DOT__cores__BRA__0__KET____DOT__genblk1__BRA__3__KET____DOT__lsu_index = 3U;
    static constexpr IData/*31:0*/ gpu__DOT__cores__BRA__1__KET____DOT__i = 1U;
    static constexpr IData/*31:0*/ gpu__DOT__cores__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__j = 0U;
    static constexpr IData/*31:0*/ gpu__DOT__cores__BRA__1__KET____DOT__genblk1__BRA__0__KET____DOT__lsu_index = 4U;
    static constexpr IData/*31:0*/ gpu__DOT__cores__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__j = 1U;
    static constexpr IData/*31:0*/ gpu__DOT__cores__BRA__1__KET____DOT__genblk1__BRA__1__KET____DOT__lsu_index = 5U;
    static constexpr IData/*31:0*/ gpu__DOT__cores__BRA__1__KET____DOT__genblk1__BRA__2__KET____DOT__j = 2U;
    static constexpr IData/*31:0*/ gpu__DOT__cores__BRA__1__KET____DOT__genblk1__BRA__2__KET____DOT__lsu_index = 6U;
    static constexpr IData/*31:0*/ gpu__DOT__cores__BRA__1__KET____DOT__genblk1__BRA__3__KET____DOT__j = 3U;
    static constexpr IData/*31:0*/ gpu__DOT__cores__BRA__1__KET____DOT__genblk1__BRA__3__KET____DOT__lsu_index = 7U;
    static constexpr IData/*31:0*/ gpu__DOT__dispatch_instance__DOT__NUM_CORES = 2U;
    static constexpr IData/*31:0*/ gpu__DOT__dispatch_instance__DOT__THREADS_PER_BLOCK = 4U;
    static constexpr IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__NUM_CONSUMERS = 8U;
    static constexpr IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__NUM_CHANNELS = 4U;
    static constexpr IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__ADDR_BITS = 8U;
    static constexpr IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__CACHE_OFFSET_BITS = 1U;
    static constexpr IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__CACHE_INDEX_BITS = 4U;
    static constexpr IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__CONSUMER_BUS_BITS = 8U;
    static constexpr IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__MEMORY_BUS_BITS = 8U;
    static constexpr IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__BITS_ADDRESSABLE = 8U;
    static constexpr IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__NUM_WORDS_IN_LINE = 2U;
    static constexpr IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__CHUNK_SIZE = 8U;
    static constexpr IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__NUM_BYTES = 2U;
    static constexpr IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__NUM_CHUNKS = 2U;
    static constexpr IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__CACHE_LINE_SIZE_BITS = 0x00000010U;
    static constexpr IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__CACHE_NUM_LINES = 0x00000010U;
    static constexpr IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__CACHE_TAG_BITS = 3U;
    static constexpr IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__0__KET____DOT__i = 0U;
    static constexpr IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__1__KET____DOT__i = 1U;
    static constexpr IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__2__KET____DOT__i = 2U;
    static constexpr IData/*31:0*/ gpu__DOT__data_memory_controller__DOT__genblk1__BRA__3__KET____DOT__i = 3U;
    static constexpr IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__NUM_CONSUMERS = 2U;
    static constexpr IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__NUM_CHANNELS = 1U;
    static constexpr IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__ADDR_BITS = 8U;
    static constexpr IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__CACHE_OFFSET_BITS = 1U;
    static constexpr IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__CACHE_INDEX_BITS = 4U;
    static constexpr IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__CONSUMER_BUS_BITS = 0x00000010U;
    static constexpr IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__MEMORY_BUS_BITS = 0x00000010U;
    static constexpr IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__BITS_ADDRESSABLE = 0x00000010U;
    static constexpr IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__NUM_WORDS_IN_LINE = 2U;
    static constexpr IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__CHUNK_SIZE = 0x00000010U;
    static constexpr IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__NUM_BYTES = 1U;
    static constexpr IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__NUM_CHUNKS = 2U;
    static constexpr IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__CACHE_LINE_SIZE_BITS = 0x00000020U;
    static constexpr IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__CACHE_NUM_LINES = 0x00000010U;
    static constexpr IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__CACHE_TAG_BITS = 3U;
    static constexpr IData/*31:0*/ gpu__DOT__program_memory_controller__DOT__genblk1__BRA__0__KET____DOT__i = 0U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
